import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // next-env.d.ts is generated by Next on every build and is not ours to style.
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "public/sw.js",
      "lib/api/**",
      "next-env.d.ts",
      "screenshots/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/no-unused-vars": ["error", {argsIgnorePattern: "^_"}],
      // Money is bigint everywhere. A stray Number() on a uint256 loses precision silently above
      // 2^53, which for an 18-decimal price is anything over about 0.009.
      "no-restricted-globals": [
        "error",
        {name: "Number", message: "Amounts are bigint. Use lib/format helpers to display them."},
      ],
    },
  },
);
