import {describe, expect, it} from "vitest";
import fixtures from "./fixtures/quotes.json";
import {confidenceBps, entryPrice, notionalUsd, quoteOpen} from "./quote";

/// quote.ts is vendored from the backend, and these are the backend's own fixtures, generated by
/// running the real contract. Running them here is what says the number the trade sheet previews
/// and the number the server quotes are the same number — which is the whole point of sharing the
/// file rather than reimplementing it.

interface Fixture {
  price: string;
  conf: string;
  collateral: string;
  openFeeBps: number;
  isLong: boolean;
  expectedNetCollateral: string;
  expectedEntryPrice: string;
  expectedUnits: string;
}

describe("quoteOpen against the contract's own fixtures", () => {
  const cases = fixtures as Fixture[];

  it("has fixtures to run", () => {
    expect(cases.length).toBeGreaterThan(0);
  });

  for (const [index, fixture] of cases.entries()) {
    const side = fixture.isLong ? "long" : "short";
    it(`case ${index} — ${side} at ${fixture.price} ± ${fixture.conf}`, () => {
      const result = quoteOpen({
        price: BigInt(fixture.price),
        conf: BigInt(fixture.conf),
        collateral: BigInt(fixture.collateral),
        openFeeBps: fixture.openFeeBps,
        isLong: fixture.isLong,
      });

      expect(result.netCollateral).toBe(BigInt(fixture.expectedNetCollateral));
      expect(result.entryPrice).toBe(BigInt(fixture.expectedEntryPrice));
      expect(result.units).toBe(BigInt(fixture.expectedUnits));
      expect(result.openFee).toBe(BigInt(fixture.collateral) - result.netCollateral);
    });
  }
});

describe("entry price", () => {
  it("moves against the trader, so a long never fills at mid", () => {
    const price = 77_000_000_000_000_000_000_000n;
    const conf = 10_000_000_000_000_000_000n;
    expect(entryPrice(price, conf, true)).toBe(price + conf);
    expect(entryPrice(price, conf, false)).toBe(price - conf);
  });
});

describe("confidenceBps", () => {
  it("expresses confidence against the asset's maxConfBps of 100", () => {
    // EUR/USD as the oracle last published it: 1.15985 ± 0.00013.
    expect(confidenceBps(1_159_850_000_000_000_000n, 130_000_000_000_000n)).toBe(1n);
  });

  it("rejects outright when there is no price to compare against", () => {
    expect(confidenceBps(0n, 1n)).toBe(10_000n);
  });
});

describe("notionalUsd", () => {
  it("scales 6-decimal collateral to the wad the caps are expressed in", () => {
    // maxPositionUsd is 25000e18; 2 USDC of collateral is 2e18 against it.
    expect(notionalUsd(2_000_000n)).toBe(2n * 10n ** 18n);
  });
});
