/// Vendored from cope-market/backend. Do not edit here.
/// Run `npm run api:sync` to update; `npm run api:check` fails if this has drifted.
/// Quote arithmetic, mirroring SyntheticVault.open exactly.
///
/// The contract has no quote view, so this is what a user is shown before they sign. It must agree
/// with the contract to the wei: quoting one number and filling another is the bug this whole
/// module exists to avoid. Parity is asserted against fixtures generated by running the real
/// contract, in quote.test.ts.
///
/// Every value here is a bigint. A JavaScript number cannot hold a uint256 and silently loses
/// precision above 2^53, which for an 18-decimal price is anything over about 0.009.

export const BPS = 10_000n;
export const WAD = 10n ** 18n;
/// 1e18 / 1e6. USDC is 6 decimals; internal maths is 18.
export const USDC_SCALE = 10n ** 12n;

export interface QuoteInput {
  price: bigint;
  conf: bigint;
  collateral: bigint;
  openFeeBps: number;
  isLong: boolean;
}

export interface QuoteResult {
  openFee: bigint;
  netCollateral: bigint;
  entryPrice: bigint;
  units: bigint;
}

/// The oracle mid moved against the trader by the confidence interval: a long enters above mid, a
/// short below. This is what absorbs oracle latency drift in the protocol's favour, and a client
/// showing the mid as the entry price would be showing a fill the user will not get.
export function entryPrice(price: bigint, conf: bigint, isLong: boolean): bigint {
  return isLong ? price + conf : price - conf;
}

/// Confidence as a fraction of price, for comparison against the asset's maxConfBps.
export function confidenceBps(price: bigint, conf: bigint): bigint {
  if (price === 0n) return BPS;
  return (conf * BPS) / price;
}

export function quoteOpen(input: QuoteInput): QuoteResult {
  // The fee is taken in 6-decimal space, matching the contract. Taking it after scaling to wad
  // would round differently and leave the position holding a collateral figure the contract
  // disagrees with.
  const openFee = (input.collateral * BigInt(input.openFeeBps)) / BPS;
  const netCollateral = input.collateral - openFee;

  const entry = entryPrice(input.price, input.conf, input.isLong);
  if (entry <= 0n) throw new Error("Confidence interval is wider than the price itself.");

  const notionalWad = netCollateral * USDC_SCALE;
  const units = (notionalWad * WAD) / entry;

  return {openFee, netCollateral, entryPrice: entry, units};
}

/// Notional in USD wad, which is what the contract compares against maxPositionUsd.
export function notionalUsd(netCollateral: bigint): bigint {
  return netCollateral * USDC_SCALE;
}
